version: 2
jobs:
  build:
    
    working_directory: ~/device-tracking

    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:

      - checkout

      - restore_cache:
          key: device-tracking-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: device-tracking-{{ checksum "pom.xml" }}
      
      - run: mvn clean build
      
      - store_artifacts:
          path: target/device-tracking-0.0.1-SNAPSHOT.jar
